version: '3'
services:
  redis:
    image: redis
  nginx:
    build: .
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
    - ./conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
    ports:
    - '8080:80'
    depends_on:
    - redis
